name: Core
version: ${project.version}
main: de.constellate.nitroapp.Main
api-version: 1.17
authors: [ DominikGralka ]
description: Nitroapp-Core for Minecraft
website: nitroapp.de

commands:
  test:
    description: A simple test command.
  backpack:
    description: A useful 9 slot backpack.
    aliases: [bp, b]
  balance:
    description: General economical query command.
    aliases: [bal, money]
  pay:
    description: Send money to your pals.
  sell:
    description: Sell the item you are currently holding.
  value:
    description: Get the value of an item.
    aliases: [val, price]
  waypoint:
    description: Creates or teleports yourself to a waypoint.
    aliases: [wp, way]
  tp:
    description: A custom teleport command.
    aliases: [teleport, tpa]
  tpaccept:
    description: Accepts a teleportation request
  maintenance:
    permission: core.maintenance
  broadcast:
    permission: core.broadcast
    aliases: [bc]